/*
 * Copyright (c) 2020. BioGraphDb
 * All rights reserved
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.03 at 08:09:53 AM PDT
//
package org.biographdb.alsdb.model.uniprot

import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlAttribute
import javax.xml.bind.annotation.XmlType

/**
 *
 * Describes different types of citations. Equivalent to the flat file RX-, RG-, RA-, RT- and RL-lines.
 *
 *
 *
 * Java class for citationType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="citationType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="editorList" type="{http://uniprot.org/uniprot}nameListType" minOccurs="0"/>
 * &lt;element name="authorList" type="{http://uniprot.org/uniprot}nameListType" minOccurs="0"/>
 * &lt;element name="locator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="dbReference" type="{http://uniprot.org/uniprot}dbReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;attribute name="type" use="required">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="book"/>
 * &lt;enumeration value="journal article"/>
 * &lt;enumeration value="online journal article"/>
 * &lt;enumeration value="patent"/>
 * &lt;enumeration value="submission"/>
 * &lt;enumeration value="thesis"/>
 * &lt;enumeration value="unpublished observations"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;attribute name="date">
 * &lt;simpleType>
 * &lt;union memberTypes=" {http://www.w3.org/2001/XMLSchema}date {http://www.w3.org/2001/XMLSchema}gYearMonth {http://www.w3.org/2001/XMLSchema}gYear">
 * &lt;/union>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="volume" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="first" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="last" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="publisher" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="city" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="db" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="institute" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="country" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "citationType", propOrder = ["title", "editorList", "authorList", "locator", "dbReference"])
class CitationType {
    /**
     * Gets the value of the title property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the title property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    var title: String? = null
    /**
     * Gets the value of the editorList property.
     *
     * @return
     * possible object is
     * [NameListType]
     */
    /**
     * Sets the value of the editorList property.
     *
     * @param value
     * allowed object is
     * [NameListType]
     */
    var editorList: NameListType? = null
    /**
     * Gets the value of the authorList property.
     *
     * @return
     * possible object is
     * [NameListType]
     */
    /**
     * Sets the value of the authorList property.
     *
     * @param value
     * allowed object is
     * [NameListType]
     */
    var authorList: NameListType? = null
    /**
     * Gets the value of the locator property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the locator property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    var locator: String? = null
    var dbReference: List<DbReferenceType>? = null

    /**
     * Gets the value of the type property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the type property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "type", required = true)
    var type: String? = null

    /**
     * Gets the value of the date property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the date property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "date")
    var date: String? = null

    /**
     * Gets the value of the name property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the name property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "name")
    var name: String? = null

    /**
     * Gets the value of the volume property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the volume property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "volume")
    var volume: String? = null

    /**
     * Gets the value of the first property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the first property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "first")
    var first: String? = null

    /**
     * Gets the value of the last property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the last property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "last")
    var last: String? = null

    /**
     * Gets the value of the publisher property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the publisher property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "publisher")
    var publisher: String? = null

    /**
     * Gets the value of the city property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the city property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "city")
    var city: String? = null

    /**
     * Gets the value of the db property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the db property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "db")
    var db: String? = null

    /**
     * Gets the value of the number property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the number property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "number")
    var number: String? = null

    /**
     * Gets the value of the institute property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the institute property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "institute")
    var institute: String? = null

    /**
     * Gets the value of the country property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the country property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "country")
    var country: String? = null

    /**
     * Gets the value of the dbReference property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dbReference property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getDbReference().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [DbReferenceType]
     *
     *
     */
//    fun getDbReference(): List<DbReferenceType>? {
//        if (dbReference == null) {
//            dbReference = ArrayList()
//        }
//        return dbReference
//    }

}