//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 08:09:53 AM PDT 
//
package org.biographdb.alsdb.model.uniprot

import java.util.*
import javax.xml.bind.annotation.*

/**
 *
 * Describes different types of general annotations. Equivalent to the flat file CC-line.
 *
 *
 *
 * Java class for commentType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="commentType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="molecule" type="{http://uniprot.org/uniprot}moleculeType" minOccurs="0"/>
 * &lt;choice minOccurs="0">
 * &lt;group ref="{http://uniprot.org/uniprot}bpcCommentGroup"/>
 * &lt;sequence>
 * &lt;element name="reaction" type="{http://uniprot.org/uniprot}reactionType"/>
 * &lt;element name="physiologicalReaction" type="{http://uniprot.org/uniprot}physiologicalReactionType" maxOccurs="2" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;sequence>
 * &lt;element name="cofactor" type="{http://uniprot.org/uniprot}cofactorType" maxOccurs="unbounded"/>
 * &lt;/sequence>
 * &lt;sequence>
 * &lt;element name="subcellularLocation" type="{http://uniprot.org/uniprot}subcellularLocationType" maxOccurs="unbounded"/>
 * &lt;/sequence>
 * &lt;element name="conflict">
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="sequence" minOccurs="0">
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;attribute name="resource" use="required">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="EMBL-CDS"/>
 * &lt;enumeration value="EMBL"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}int" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * &lt;/element>
 * &lt;/sequence>
 * &lt;attribute name="type" use="required">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="frameshift"/>
 * &lt;enumeration value="erroneous initiation"/>
 * &lt;enumeration value="erroneous termination"/>
 * &lt;enumeration value="erroneous gene model prediction"/>
 * &lt;enumeration value="erroneous translation"/>
 * &lt;enumeration value="miscellaneous discrepancy"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * &lt;/element>
 * &lt;sequence>
 * &lt;element name="link" maxOccurs="unbounded" minOccurs="0">
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * &lt;/element>
 * &lt;/sequence>
 * &lt;sequence>
 * &lt;element name="event" type="{http://uniprot.org/uniprot}eventType" maxOccurs="4"/>
 * &lt;element name="isoform" type="{http://uniprot.org/uniprot}isoformType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;sequence>
 * &lt;element name="interactant" type="{http://uniprot.org/uniprot}interactantType" maxOccurs="2" minOccurs="2"/>
 * &lt;element name="organismsDiffer" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 * &lt;element name="experiments" type="{http://www.w3.org/2001/XMLSchema}int"/>
 * &lt;/sequence>
 * &lt;element name="disease">
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 * &lt;element name="acronym" type="{http://www.w3.org/2001/XMLSchema}string"/>
 * &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 * &lt;element name="dbReference" type="{http://uniprot.org/uniprot}dbReferenceType"/>
 * &lt;/sequence>
 * &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * &lt;/element>
 * &lt;/choice>
 * &lt;element name="location" type="{http://uniprot.org/uniprot}locationType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="text" type="{http://uniprot.org/uniprot}evidencedStringType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;attribute name="type" use="required">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="allergen"/>
 * &lt;enumeration value="alternative products"/>
 * &lt;enumeration value="biotechnology"/>
 * &lt;enumeration value="biophysicochemical properties"/>
 * &lt;enumeration value="catalytic activity"/>
 * &lt;enumeration value="caution"/>
 * &lt;enumeration value="cofactor"/>
 * &lt;enumeration value="developmental stage"/>
 * &lt;enumeration value="disease"/>
 * &lt;enumeration value="domain"/>
 * &lt;enumeration value="disruption phenotype"/>
 * &lt;enumeration value="activity regulation"/>
 * &lt;enumeration value="function"/>
 * &lt;enumeration value="induction"/>
 * &lt;enumeration value="miscellaneous"/>
 * &lt;enumeration value="pathway"/>
 * &lt;enumeration value="pharmaceutical"/>
 * &lt;enumeration value="polymorphism"/>
 * &lt;enumeration value="PTM"/>
 * &lt;enumeration value="RNA editing"/>
 * &lt;enumeration value="similarity"/>
 * &lt;enumeration value="subcellular location"/>
 * &lt;enumeration value="sequence caution"/>
 * &lt;enumeration value="subunit"/>
 * &lt;enumeration value="tissue specificity"/>
 * &lt;enumeration value="toxic dose"/>
 * &lt;enumeration value="online information"/>
 * &lt;enumeration value="mass spectrometry"/>
 * &lt;enumeration value="interaction"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;attribute name="locationType" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="mass" type="{http://www.w3.org/2001/XMLSchema}float" />
 * &lt;attribute name="error" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="method" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;attribute name="evidence" type="{http://uniprot.org/uniprot}intListType" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "commentType", propOrder = ["molecule", "absorption", "kinetics",
        "phDependence", "redoxPotential", "temperatureDependence", "reaction", "physiologicalReaction",
        "cofactor", "subcellularLocation", "conflict", "link", "event", "isoform", "interactant",
        "organismsDiffer", "experiments", "disease", "location", "text"]
)
class CommentType {
    /**
     * Gets the value of the molecule property.
     *
     * @return
     * possible object is
     * [MoleculeType]
     */
    /**
     * Sets the value of the molecule property.
     *
     * @param value
     * allowed object is
     * [MoleculeType]
     */
    var molecule: MoleculeType? = null
    /**
     * Gets the value of the absorption property.
     *
     * @return
     * possible object is
     * [CommentType.Absorption]
     */
    /**
     * Sets the value of the absorption property.
     *
     * @param value
     * allowed object is
     * [CommentType.Absorption]
     */
    var absorption: Absorption? = null
    /**
     * Gets the value of the kinetics property.
     *
     * @return
     * possible object is
     * [CommentType.Kinetics]
     */
    /**
     * Sets the value of the kinetics property.
     *
     * @param value
     * allowed object is
     * [CommentType.Kinetics]
     */
    var kinetics: Kinetics? = null
    /**
     * Gets the value of the phDependence property.
     *
     * @return
     * possible object is
     * [CommentType.PhDependence]
     */
    /**
     * Sets the value of the phDependence property.
     *
     * @param value
     * allowed object is
     * [CommentType.PhDependence]
     */
    var phDependence: PhDependence? = null
    /**
     * Gets the value of the redoxPotential property.
     *
     * @return
     * possible object is
     * [CommentType.RedoxPotential]
     */
    /**
     * Sets the value of the redoxPotential property.
     *
     * @param value
     * allowed object is
     * [CommentType.RedoxPotential]
     */
    var redoxPotential: RedoxPotential? = null
    /**
     * Gets the value of the temperatureDependence property.
     *
     * @return
     * possible object is
     * [CommentType.TemperatureDependence]
     */
    /**
     * Sets the value of the temperatureDependence property.
     *
     * @param value
     * allowed object is
     * [CommentType.TemperatureDependence]
     */
    var temperatureDependence: TemperatureDependence? = null
    /**
     * Gets the value of the reaction property.
     *
     * @return
     * possible object is
     * [ReactionType]
     */
    /**
     * Sets the value of the reaction property.
     *
     * @param value
     * allowed object is
     * [ReactionType]
     */
    var reaction: ReactionType? = null
    protected var physiologicalReaction: List<PhysiologicalReactionType>? = null
    protected var cofactor: List<CofactorType>? = null
    protected var subcellularLocation: List<SubcellularLocationType>? = null
    /**
     * Gets the value of the conflict property.
     *
     * @return
     * possible object is
     * [CommentType.Conflict]
     */
    /**
     * Sets the value of the conflict property.
     *
     * @param value
     * allowed object is
     * [CommentType.Conflict]
     */
    var conflict: Conflict? = null
    protected var link: List<Link>? = null
    protected var event: List<EventType>? = null
    protected var isoform: List<IsoformType>? = null
    protected var interactant: List<InteractantType>? = null

    /**
     * Gets the value of the organismsDiffer property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the organismsDiffer property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(defaultValue = "false")
    var organismsDiffer: Boolean? = null
    /**
     * Gets the value of the experiments property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the experiments property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    var experiments: Int? = null
    /**
     * Gets the value of the disease property.
     *
     * @return
     * possible object is
     * [CommentType.Disease]
     */
    /**
     * Sets the value of the disease property.
     *
     * @param value
     * allowed object is
     * [CommentType.Disease]
     */
    var disease: Disease? = null
    protected var location: List<LocationType>? = null
    protected var text: List<EvidencedStringType>? = null

    /**
     * Gets the value of the type property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the type property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "type", required = true)
    var type: String? = null

    /**
     * Gets the value of the locationType property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the locationType property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "locationType")
    var locationType: String? = null

    /**
     * Gets the value of the name property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the name property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "name")
    var name: String? = null

    /**
     * Gets the value of the mass property.
     *
     * @return
     * possible object is
     * [Float]
     */
    /**
     * Sets the value of the mass property.
     *
     * @param value
     * allowed object is
     * [Float]
     */
    @XmlAttribute(name = "mass")
    var mass: Float? = null

    /**
     * Gets the value of the error property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the error property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "error")
    var error: String? = null

    /**
     * Gets the value of the method property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the method property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "method")
    var method: String? = null

    @XmlAttribute(name = "evidence")
    protected var evidence: List<Int>? = null

    /**
     * Gets the value of the physiologicalReaction property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the physiologicalReaction property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getPhysiologicalReaction().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [PhysiologicalReactionType]
     *
     *
     */
//    fun getPhysiologicalReaction(): List<PhysiologicalReactionType>? {
//        if (physiologicalReaction == null) {
//            physiologicalReaction = ArrayList()
//        }
//        return physiologicalReaction
//    }

    /**
     * Gets the value of the cofactor property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cofactor property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getCofactor().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [CofactorType]
     *
     *
     */
//    fun getCofactor(): List<CofactorType>? {
//        if (cofactor == null) {
//            cofactor = ArrayList()
//        }
//        return cofactor
//    }

    /**
     * Gets the value of the subcellularLocation property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subcellularLocation property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getSubcellularLocation().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [SubcellularLocationType]
     *
     *
     */
//    fun getSubcellularLocation(): List<SubcellularLocationType>? {
//        if (subcellularLocation == null) {
//            subcellularLocation = ArrayList()
//        }
//        return subcellularLocation
//    }

    /**
     * Gets the value of the link property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the link property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getLink().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [CommentType.Link]
     *
     *
     */
//    fun getLink(): List<Link>? {
//        if (link == null) {
//            link = ArrayList()
//        }
//        return link
//    }

    /**
     * Gets the value of the event property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the event property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getEvent().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [EventType]
     *
     *
     */
//    fun getEvent(): List<EventType>? {
//        if (event == null) {
//            event = ArrayList()
//        }
//        return event
//    }

    /**
     * Gets the value of the isoform property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isoform property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getIsoform().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [IsoformType]
     *
     *
     */
//    fun getIsoform(): List<IsoformType>? {
//        if (isoform == null) {
//            isoform = ArrayList()
//        }
//        return isoform
//    }

    /**
     * Gets the value of the interactant property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interactant property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getInteractant().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [InteractantType]
     *
     *
     */
//    fun getInteractant(): List<InteractantType>? {
//        if (interactant == null) {
//            interactant = ArrayList()
//        }
//        return interactant
//    }

    /**
     * Gets the value of the location property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the location property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getLocation().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [LocationType]
     *
     *
     */
//    fun getLocation(): List<LocationType>? {
//        if (location == null) {
//            location = ArrayList()
//        }
//        return location
//    }

    /**
     * Gets the value of the text property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the text property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getText().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [EvidencedStringType]
     *
     *
     */
//    fun getText(): List<EvidencedStringType>? {
//        if (text == null) {
//            text = ArrayList()
//        }
//        return text
//    }

    /**
     * Gets the value of the evidence property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evidence property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getEvidence().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [Integer]
     *
     *
     */
//    fun getEvidence(): List<Int>? {
//        if (evidence == null) {
//            evidence = ArrayList()
//        }
//        return evidence
//    }

    /**
     *
     * Java class for anonymous complex type.
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;sequence>
     * &lt;element name="max" type="{http://uniprot.org/uniprot}evidencedStringType" minOccurs="0"/>
     * &lt;element name="text" type="{http://uniprot.org/uniprot}evidencedStringType" maxOccurs="unbounded" minOccurs="0"/>
     * &lt;/sequence>
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
    </pre> *
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = ["max", "text"])
    class Absorption {
        /**
         * Gets the value of the max property.
         *
         * @return
         * possible object is
         * [EvidencedStringType]
         */
        /**
         * Sets the value of the max property.
         *
         * @param value
         * allowed object is
         * [EvidencedStringType]
         */
        var max: EvidencedStringType? = null
        protected var text: List<EvidencedStringType>? = null

        /**
         * Gets the value of the text property.
         *
         *
         *
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the text property.
         *
         *
         *
         * For example, to add a new item, do as follows:
         * <pre>
         * getText().add(newItem);
        </pre> *
         *
         *
         *
         *
         * Objects of the following type(s) are allowed in the list
         * [EvidencedStringType]
         *
         *
         */
//        fun getText(): List<EvidencedStringType>? {
//            if (text == null) {
//                text = ArrayList()
//            }
//            return text
//        }
    }

    /**
     *
     * Java class for anonymous complex type.
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;sequence>
     * &lt;element name="sequence" minOccurs="0">
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;attribute name="resource" use="required">
     * &lt;simpleType>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     * &lt;enumeration value="EMBL-CDS"/>
     * &lt;enumeration value="EMBL"/>
     * &lt;/restriction>
     * &lt;/simpleType>
     * &lt;/attribute>
     * &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     * &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}int" />
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
     * &lt;/element>
     * &lt;/sequence>
     * &lt;attribute name="type" use="required">
     * &lt;simpleType>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     * &lt;enumeration value="frameshift"/>
     * &lt;enumeration value="erroneous initiation"/>
     * &lt;enumeration value="erroneous termination"/>
     * &lt;enumeration value="erroneous gene model prediction"/>
     * &lt;enumeration value="erroneous translation"/>
     * &lt;enumeration value="miscellaneous discrepancy"/>
     * &lt;/restriction>
     * &lt;/simpleType>
     * &lt;/attribute>
     * &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}string" />
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
    </pre> *
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = ["sequence"])
    class Conflict {
        /**
         * Gets the value of the sequence property.
         *
         * @return
         * possible object is
         * [CommentType.Conflict.Sequence]
         */
        /**
         * Sets the value of the sequence property.
         *
         * @param value
         * allowed object is
         * [CommentType.Conflict.Sequence]
         */
        var sequence: Sequence? = null

        /**
         * Gets the value of the type property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the type property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlAttribute(name = "type", required = true)
        var type: String? = null

        /**
         * Gets the value of the ref property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the ref property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlAttribute(name = "ref")
        var ref: String? = null

        /**
         *
         * Java class for anonymous complex type.
         *
         *
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         * &lt;complexContent>
         * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         * &lt;attribute name="resource" use="required">
         * &lt;simpleType>
         * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         * &lt;enumeration value="EMBL-CDS"/>
         * &lt;enumeration value="EMBL"/>
         * &lt;/restriction>
         * &lt;/simpleType>
         * &lt;/attribute>
         * &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         * &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}int" />
         * &lt;/restriction>
         * &lt;/complexContent>
         * &lt;/complexType>
        </pre> *
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        class Sequence {
            /**
             * Gets the value of the resource property.
             *
             * @return
             * possible object is
             * [String]
             */
            /**
             * Sets the value of the resource property.
             *
             * @param value
             * allowed object is
             * [String]
             */
            @XmlAttribute(name = "resource", required = true)
            var resource: String? = null

            /**
             * Gets the value of the id property.
             *
             * @return
             * possible object is
             * [String]
             */
            /**
             * Sets the value of the id property.
             *
             * @param value
             * allowed object is
             * [String]
             */
            @XmlAttribute(name = "id", required = true)
            var id: String? = null

            /**
             * Gets the value of the version property.
             *
             * @return
             * possible object is
             * [Integer]
             */
            /**
             * Sets the value of the version property.
             *
             * @param value
             * allowed object is
             * [Integer]
             */
            @XmlAttribute(name = "version")
            var version: Int? = null

        }
    }

    /**
     *
     * Java class for anonymous complex type.
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;sequence>
     * &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     * &lt;element name="acronym" type="{http://www.w3.org/2001/XMLSchema}string"/>
     * &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     * &lt;element name="dbReference" type="{http://uniprot.org/uniprot}dbReferenceType"/>
     * &lt;/sequence>
     * &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
    </pre> *
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = ["name", "acronym", "description", "dbReference"])
    class Disease {
        /**
         * Gets the value of the name property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the name property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(required = true)
        var name: String? = null

        /**
         * Gets the value of the acronym property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the acronym property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(required = true)
        var acronym: String? = null

        /**
         * Gets the value of the description property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the description property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(required = true)
        var description: String? = null

        /**
         * Gets the value of the dbReference property.
         *
         * @return
         * possible object is
         * [DbReferenceType]
         */
        /**
         * Sets the value of the dbReference property.
         *
         * @param value
         * allowed object is
         * [DbReferenceType]
         */
        @XmlElement(required = true)
        var dbReference: DbReferenceType? = null

        /**
         * Gets the value of the id property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the id property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlAttribute(name = "id", required = true)
        var id: String? = null

    }

    /**
     *
     * Java class for anonymous complex type.
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;sequence>
     * &lt;element name="KM" type="{http://uniprot.org/uniprot}evidencedStringType" maxOccurs="unbounded" minOccurs="0"/>
     * &lt;element name="Vmax" type="{http://uniprot.org/uniprot}evidencedStringType" maxOccurs="unbounded" minOccurs="0"/>
     * &lt;element name="text" type="{http://uniprot.org/uniprot}evidencedStringType" maxOccurs="unbounded" minOccurs="0"/>
     * &lt;/sequence>
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
    </pre> *
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = ["km", "vmax", "text"])
    class Kinetics {
        @XmlElement(name = "KM")
        protected var km: List<EvidencedStringType>? = null

        @XmlElement(name = "Vmax")
        protected var vmax: List<EvidencedStringType>? = null
        protected var text: List<EvidencedStringType>? = null

        /**
         * Gets the value of the km property.
         *
         *
         *
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the km property.
         *
         *
         *
         * For example, to add a new item, do as follows:
         * <pre>
         * getKM().add(newItem);
        </pre> *
         *
         *
         *
         *
         * Objects of the following type(s) are allowed in the list
         * [EvidencedStringType]
         *
         *
         */
        val kM: List<EvidencedStringType>?
            get() {
                if (km == null) {
                    km = ArrayList()
                }
                return km
            }

        /**
         * Gets the value of the vmax property.
         *
         *
         *
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vmax property.
         *
         *
         *
         * For example, to add a new item, do as follows:
         * <pre>
         * getVmax().add(newItem);
        </pre> *
         *
         *
         *
         *
         * Objects of the following type(s) are allowed in the list
         * [EvidencedStringType]
         *
         *
         */
//        fun getVmax(): List<EvidencedStringType>? {
//            if (vmax == null) {
//                vmax = ArrayList()
//            }
//            return vmax
//        }

        /**
         * Gets the value of the text property.
         *
         *
         *
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the text property.
         *
         *
         *
         * For example, to add a new item, do as follows:
         * <pre>
         * getText().add(newItem);
        </pre> *
         *
         *
         *
         *
         * Objects of the following type(s) are allowed in the list
         * [EvidencedStringType]
         *
         *
         */
//        fun getText(): List<EvidencedStringType>? {
//            if (text == null) {
//                text = ArrayList()
//            }
//            return text
//        }
    }

    /**
     *
     * Java class for anonymous complex type.
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
    </pre> *
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    class Link {
        /**
         * Gets the value of the uri property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the uri property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlAttribute(name = "uri", required = true)
        @XmlSchemaType(name = "anyURI")
        var uri: String? = null

    }

    /**
     *
     * Java class for anonymous complex type.
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;sequence>
     * &lt;element name="text" type="{http://uniprot.org/uniprot}evidencedStringType" maxOccurs="unbounded"/>
     * &lt;/sequence>
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
    </pre> *
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = ["text"])
    class PhDependence {
        @XmlElement(required = true)
        protected var text: List<EvidencedStringType>? = null

        /**
         * Gets the value of the text property.
         *
         *
         *
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the text property.
         *
         *
         *
         * For example, to add a new item, do as follows:
         * <pre>
         * getText().add(newItem);
        </pre> *
         *
         *
         *
         *
         * Objects of the following type(s) are allowed in the list
         * [EvidencedStringType]
         *
         *
         */
//        fun getText(): List<EvidencedStringType>? {
//            if (text == null) {
//                text = ArrayList()
//            }
//            return text
//        }
    }

    /**
     *
     * Java class for anonymous complex type.
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;sequence>
     * &lt;element name="text" type="{http://uniprot.org/uniprot}evidencedStringType" maxOccurs="unbounded"/>
     * &lt;/sequence>
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
    </pre> *
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = ["text"])
    class RedoxPotential {
        @XmlElement(required = true)
        protected var text: List<EvidencedStringType>? = null

        /**
         * Gets the value of the text property.
         *
         *
         *
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the text property.
         *
         *
         *
         * For example, to add a new item, do as follows:
         * <pre>
         * getText().add(newItem);
        </pre> *
         *
         *
         *
         *
         * Objects of the following type(s) are allowed in the list
         * [EvidencedStringType]
         *
         *
         */
//        fun getText(): List<EvidencedStringType>? {
//            if (text == null) {
//                text = ArrayList()
//            }
//            return text
//        }
    }

    /**
     *
     * Java class for anonymous complex type.
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;sequence>
     * &lt;element name="text" type="{http://uniprot.org/uniprot}evidencedStringType" maxOccurs="unbounded"/>
     * &lt;/sequence>
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
    </pre> *
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = ["text"])
    class TemperatureDependence {
        @XmlElement(required = true)
        protected var text: List<EvidencedStringType>? = null

        /**
         * Gets the value of the text property.
         *
         *
         *
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the text property.
         *
         *
         *
         * For example, to add a new item, do as follows:
         * <pre>
         * getText().add(newItem);
        </pre> *
         *
         *
         *
         *
         * Objects of the following type(s) are allowed in the list
         * [EvidencedStringType]
         *
         *
         */
//        fun getText(): List<EvidencedStringType>? {
//            if (text == null) {
//                text = ArrayList()
//            }
//            return text
//        }
    }
}