//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 08:09:53 AM PDT 
//
package org.biographdb.alsdb.model.uniprot

import java.util.*
import javax.xml.bind.annotation.*
import javax.xml.datatype.XMLGregorianCalendar

/**
 *
 * Java class for anonymous complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="accession" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 * &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 * &lt;element name="protein" type="{http://uniprot.org/uniprot}proteinType"/>
 * &lt;element name="gene" type="{http://uniprot.org/uniprot}geneType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="organism" type="{http://uniprot.org/uniprot}organismType"/>
 * &lt;element name="organismHost" type="{http://uniprot.org/uniprot}organismType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="geneLocation" type="{http://uniprot.org/uniprot}geneLocationType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="reference" type="{http://uniprot.org/uniprot}referenceType" maxOccurs="unbounded"/>
 * &lt;element name="comment" type="{http://uniprot.org/uniprot}commentType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="dbReference" type="{http://uniprot.org/uniprot}dbReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="proteinExistence" type="{http://uniprot.org/uniprot}proteinExistenceType"/>
 * &lt;element name="keyword" type="{http://uniprot.org/uniprot}keywordType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="feature" type="{http://uniprot.org/uniprot}featureType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="evidence" type="{http://uniprot.org/uniprot}evidenceType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="sequence" type="{http://uniprot.org/uniprot}sequenceType"/>
 * &lt;/sequence>
 * &lt;attribute name="dataset" use="required">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Swiss-Prot"/>
 * &lt;enumeration value="TrEMBL"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;attribute name="created" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 * &lt;attribute name="modified" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 * &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = ["accession", "name", "protein", "gene", "organism", "organismHost", "geneLocation", "reference", "comment",
        "dbReference", "proteinExistence", "keyword", "feature", "evidence", "sequence"]
)
@XmlRootElement(name = "entry")
class Entry {
    @XmlElement(required = true)
    protected var accession: List<String>? = null

    @XmlElement(required = true)
    protected var name: List<String>? = null

    /**
     * Gets the value of the protein property.
     *
     * @return
     * possible object is
     * [ProteinType]
     */
    /**
     * Sets the value of the protein property.
     *
     * @param value
     * allowed object is
     * [ProteinType]
     */
    @XmlElement(required = true)
    var protein: ProteinType? = null
    protected var gene: List<GeneType>? = null

    /**
     * Gets the value of the organism property.
     *
     * @return
     * possible object is
     * [OrganismType]
     */
    /**
     * Sets the value of the organism property.
     *
     * @param value
     * allowed object is
     * [OrganismType]
     */
    @XmlElement(required = true)
    var organism: OrganismType? = null
    protected var organismHost: List<OrganismType>? = null
    protected var geneLocation: List<GeneLocationType>? = null

    @XmlElement(required = true)
    protected var reference: List<ReferenceType>? = null

    @XmlElement(nillable = true)
    protected var comment: List<CommentType>? = null
    protected var dbReference: List<DbReferenceType>? = null

    /**
     * Gets the value of the proteinExistence property.
     *
     * @return
     * possible object is
     * [ProteinExistenceType]
     */
    /**
     * Sets the value of the proteinExistence property.
     *
     * @param value
     * allowed object is
     * [ProteinExistenceType]
     */
    @XmlElement(required = true)
    var proteinExistence: ProteinExistenceType? = null
    protected var keyword: List<KeywordType>? = null
    protected var feature: List<FeatureType>? = null
    protected var evidence: List<EvidenceType>? = null

    /**
     * Gets the value of the sequence property.
     *
     * @return
     * possible object is
     * [SequenceType]
     */
    /**
     * Sets the value of the sequence property.
     *
     * @param value
     * allowed object is
     * [SequenceType]
     */
    @XmlElement(required = true)
    var sequence: SequenceType? = null

    /**
     * Gets the value of the dataset property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the dataset property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "dataset", required = true)
    var dataset: String? = null

    /**
     * Gets the value of the created property.
     *
     * @return
     * possible object is
     * [XMLGregorianCalendar]
     */
    /**
     * Sets the value of the created property.
     *
     * @param value
     * allowed object is
     * [XMLGregorianCalendar]
     */
    @XmlAttribute(name = "created", required = true)
    @XmlSchemaType(name = "date")
    var created: XMLGregorianCalendar? = null

    /**
     * Gets the value of the modified property.
     *
     * @return
     * possible object is
     * [XMLGregorianCalendar]
     */
    /**
     * Sets the value of the modified property.
     *
     * @param value
     * allowed object is
     * [XMLGregorianCalendar]
     */
    @XmlAttribute(name = "modified", required = true)
    @XmlSchemaType(name = "date")
    var modified: XMLGregorianCalendar? = null

    /**
     * Gets the value of the version property.
     *
     */
    /**
     * Sets the value of the version property.
     *
     */
    @XmlAttribute(name = "version", required = true)
    var version = 0

    /**
     * Gets the value of the accession property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accession property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getAccession().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [String]
     *
     *
     */
    fun getAccessionList(): List<String>? {
        if (accession == null) {
            accession = ArrayList()
        }
        return accession
    }

    /**
     * Gets the value of the name property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getName().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [String]
     *
     *
     */
    fun getNameList(): List<String>? {
        if (name == null) {
            name = ArrayList()
        }
        return name
    }

    /**
     * Gets the value of the gene property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gene property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getGene().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [GeneType]
     *
     *
     */
    fun getGeneList(): List<GeneType>? {
        if (gene == null) {
            gene = ArrayList()
        }
        return gene
    }

    /**
     * Gets the value of the organismHost property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organismHost property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getOrganismHost().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [OrganismType]
     *
     *
     */
    fun getOrganismHostList(): List<OrganismType>? {
        if (organismHost == null) {
            organismHost = ArrayList()
        }
        return organismHost
    }

    /**
     * Gets the value of the geneLocation property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geneLocation property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getGeneLocation().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [GeneLocationType]
     *
     *
     */
    fun getGeneLocationList(): List<GeneLocationType>? {
        if (geneLocation == null) {
            geneLocation = ArrayList()
        }
        return geneLocation
    }

    /**
     * Gets the value of the reference property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reference property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getReference().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [ReferenceType]
     *
     *
     */
    fun getReferenceList(): List<ReferenceType>? {
        if (reference == null) {
            reference = ArrayList()
        }
        return reference
    }

    /**
     * Gets the value of the comment property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comment property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getComment().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [CommentType]
     *
     *
     */
    fun getCommentList(): List<CommentType>? {
        if (comment == null) {
            comment = ArrayList()
        }
        return comment
    }

    /**
     * Gets the value of the dbReference property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dbReference property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getDbReference().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [DbReferenceType]
     *
     *
     */
    fun getDbReferenceList(): List<DbReferenceType>? {
        if (dbReference == null) {
            dbReference = ArrayList()
        }
        return dbReference
    }

    /**
     * Gets the value of the keyword property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyword property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getKeyword().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [KeywordType]
     *
     *
     */
    fun getKeywordList(): List<KeywordType>? {
        if (keyword == null) {
            keyword = ArrayList()
        }
        return keyword
    }

    /**
     * Gets the value of the feature property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the feature property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getFeature().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [FeatureType]
     *
     *
     */
    fun getFeatureList(): List<FeatureType>? {
        if (feature == null) {
            feature = ArrayList()
        }
        return feature
    }

    /**
     * Gets the value of the evidence property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evidence property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getEvidence().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [EvidenceType]
     *
     *
     */
    fun getEvidenceList(): List<EvidenceType>? {
        if (evidence == null) {
            evidence = ArrayList()
        }
        return evidence
    }

}