//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 08:09:53 AM PDT 
//
package org.biographdb.alsdb.model.uniprot

import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlAttribute
import javax.xml.bind.annotation.XmlType

/**
 *
 * Java class for interactantType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="interactantType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;group ref="{http://uniprot.org/uniprot}interactantGroup" minOccurs="0"/>
 * &lt;attribute name="intactId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "interactantType", propOrder = ["id", "label", "dbReference"])
class InteractantType {
    /**
     * Gets the value of the id property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the id property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    var id: String? = null
    /**
     * Gets the value of the label property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the label property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    var label: String? = null
    /**
     * Gets the value of the dbReference property.
     *
     * @return
     * possible object is
     * [DbReferenceType]
     */
    /**
     * Sets the value of the dbReference property.
     *
     * @param value
     * allowed object is
     * [DbReferenceType]
     */
    var dbReference: DbReferenceType? = null

    /**
     * Gets the value of the intactId property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the intactId property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "intactId", required = true)
    var intactId: String? = null

}