//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 08:09:53 AM PDT 
//
package org.biographdb.alsdb.model.uniprot

import java.util.*
import javax.xml.bind.annotation.*

/**
 *
 * Describes isoforms in 'alternative products' annotations.
 *
 *
 *
 * Java class for isoformType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="isoformType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 * &lt;element name="name" maxOccurs="unbounded">
 * &lt;complexType>
 * &lt;simpleContent>
 * &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 * &lt;attribute name="evidence" type="{http://uniprot.org/uniprot}intListType" />
 * &lt;/extension>
 * &lt;/simpleContent>
 * &lt;/complexType>
 * &lt;/element>
 * &lt;element name="sequence">
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;attribute name="type" use="required">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="not described"/>
 * &lt;enumeration value="described"/>
 * &lt;enumeration value="displayed"/>
 * &lt;enumeration value="external"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * &lt;/element>
 * &lt;element name="text" type="{http://uniprot.org/uniprot}evidencedStringType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "isoformType", propOrder = ["id", "name", "sequence", "text"])
class IsoformType {
    @XmlElement(required = true)
    protected var id: List<String>? = null

    @XmlElement(required = true)
    protected var name: List<Name>? = null

    /**
     * Gets the value of the sequence property.
     *
     * @return
     * possible object is
     * [IsoformType.Sequence]
     */
    /**
     * Sets the value of the sequence property.
     *
     * @param value
     * allowed object is
     * [IsoformType.Sequence]
     */
    @XmlElement(required = true)
    var sequence: Sequence? = null
    protected var text: List<EvidencedStringType>? = null

    /**
     * Gets the value of the id property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getId().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [String]
     *
     *
     */
    fun getIdList(): List<String>? {
        if (id == null) {
            id = ArrayList()
        }
        return id
    }

    /**
     * Gets the value of the name property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getName().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [IsoformType.Name]
     *
     *
     */
    fun getNameList(): List<Name>? {
        if (name == null) {
            name = ArrayList()
        }
        return name
    }

    /**
     * Gets the value of the text property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the text property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getText().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [EvidencedStringType]
     *
     *
     */
    fun getTextList(): List<EvidencedStringType>? {
        if (text == null) {
            text = ArrayList()
        }
        return text
    }

    /**
     *
     * Java class for anonymous complex type.
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     * &lt;simpleContent>
     * &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     * &lt;attribute name="evidence" type="{http://uniprot.org/uniprot}intListType" />
     * &lt;/extension>
     * &lt;/simpleContent>
     * &lt;/complexType>
    </pre> *
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = ["value"])
    class Name {
        /**
         * Gets the value of the value property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the value property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlValue
        var value: String? = null

        @XmlAttribute(name = "evidence")
        protected var evidence: List<Int>? = null

        /**
         * Gets the value of the evidence property.
         *
         *
         *
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the evidence property.
         *
         *
         *
         * For example, to add a new item, do as follows:
         * <pre>
         * getEvidence().add(newItem);
        </pre> *
         *
         *
         *
         *
         * Objects of the following type(s) are allowed in the list
         * [Integer]
         *
         *
         */
        fun getEvidenceList(): List<Int>? {
            if (evidence == null) {
                evidence = ArrayList()
            }
            return evidence
        }
    }

    /**
     *
     * Java class for anonymous complex type.
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;attribute name="type" use="required">
     * &lt;simpleType>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     * &lt;enumeration value="not described"/>
     * &lt;enumeration value="described"/>
     * &lt;enumeration value="displayed"/>
     * &lt;enumeration value="external"/>
     * &lt;/restriction>
     * &lt;/simpleType>
     * &lt;/attribute>
     * &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}string" />
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
    </pre> *
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    class Sequence {
        /**
         * Gets the value of the type property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the type property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlAttribute(name = "type", required = true)
        var type: String? = null

        /**
         * Gets the value of the ref property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the ref property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlAttribute(name = "ref")
        var ref: String? = null

    }
}