/*
 * Copyright (c) 2020. BioGraphDb
 * All rights reserved
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 08:09:53 AM PDT 
//
package org.biographdb.alsdb.model.uniprot

import java.util.*
import javax.xml.bind.annotation.*

/**
 * Describes a physiological reaction.
 *
 *
 * Java class for physiologicalReactionType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="physiologicalReactionType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="dbReference" type="{http://uniprot.org/uniprot}dbReferenceType"/>
 * &lt;/sequence>
 * &lt;attribute name="direction" use="required">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="left-to-right"/>
 * &lt;enumeration value="right-to-left"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;attribute name="evidence" type="{http://uniprot.org/uniprot}intListType" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "physiologicalReactionType", propOrder = ["dbReference"])
class PhysiologicalReactionType {
    /**
     * Gets the value of the dbReference property.
     *
     * @return
     * possible object is
     * [DbReferenceType]
     */
    /**
     * Sets the value of the dbReference property.
     *
     * @param value
     * allowed object is
     * [DbReferenceType]
     */
    @XmlElement(required = true)
    var dbReference: DbReferenceType? = null

    /**
     * Gets the value of the direction property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the direction property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "direction", required = true)
    var direction: String? = null

    @XmlAttribute(name = "evidence")
    protected var evidence: List<Int>? = null

    /**
     * Gets the value of the evidence property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evidence property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getEvidence().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [Integer]
     *
     *
     */
    fun getEvidenceList(): List<Int>? {
        if (evidence == null) {
            evidence = ArrayList()
        }
        return evidence
    }
}