//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 08:09:53 AM PDT 
//
package org.biographdb.alsdb.model.uniprot

import java.math.BigInteger
import java.util.*
import javax.xml.bind.annotation.*

/**
 *
 * Java class for positionType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="positionType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;attribute name="position" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 * &lt;attribute name="status" default="certain">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="certain"/>
 * &lt;enumeration value="uncertain"/>
 * &lt;enumeration value="less than"/>
 * &lt;enumeration value="greater than"/>
 * &lt;enumeration value="unknown"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;attribute name="evidence" type="{http://uniprot.org/uniprot}intListType" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "positionType")
class PositionType {
    /**
     * Gets the value of the position property.
     *
     * @return
     * possible object is
     * [BigInteger]
     */
    /**
     * Sets the value of the position property.
     *
     * @param value
     * allowed object is
     * [BigInteger]
     */
    @XmlAttribute(name = "position")
    @XmlSchemaType(name = "unsignedLong")
    var position: BigInteger? = null

    @XmlAttribute(name = "status")
    protected var status: String? = null

    @XmlAttribute(name = "evidence")
    protected var evidence: List<Int>? = null

    /**
     * Gets the value of the status property.
     *
     * @return
     * possible object is
     * [String]
     */
//    fun getStatus(): String {
//        return if (status == null) {
//            "certain"
//        } else {
//            status
//        }
//    }

    /**
     * Sets the value of the status property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    fun setStatusList(value: String?) {
        status = value
    }

    /**
     * Gets the value of the evidence property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evidence property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getEvidence().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [Integer]
     *
     *
     */
    fun getEvidenceList(): List<Int>? {
        if (evidence == null) {
            evidence = ArrayList()
        }
        return evidence
    }
}