//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 08:09:53 AM PDT 
//
package org.biographdb.alsdb.model.uniprot

import java.util.*
import javax.xml.bind.annotation.*

/**
 *
 * Describes a citation and a summary of its content. Equivalent to the flat file RN-, RP-, RC-, RX-, RG-, RA-, RT- and RL-lines.
 *
 *
 *
 * Java class for referenceType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="referenceType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="citation" type="{http://uniprot.org/uniprot}citationType"/>
 * &lt;group ref="{http://uniprot.org/uniprot}sptrCitationGroup"/>
 * &lt;/sequence>
 * &lt;attribute name="evidence" type="{http://uniprot.org/uniprot}intListType" />
 * &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "referenceType", propOrder = ["citation", "scope", "source"])
class ReferenceType {
    /**
     * Gets the value of the citation property.
     *
     * @return
     * possible object is
     * [CitationType]
     */
    /**
     * Sets the value of the citation property.
     *
     * @param value
     * allowed object is
     * [CitationType]
     */
    @XmlElement(required = true)
    lateinit var citation: CitationType

    @XmlElement(required = true)
    protected var scope: List<String>? = null
    /**
     * Gets the value of the source property.
     *
     * @return
     * possible object is
     * [SourceDataType]
     */
    /**
     * Sets the value of the source property.
     *
     * @param value
     * allowed object is
     * [SourceDataType]
     */
    var source: SourceDataType? = null

    @XmlAttribute(name = "evidence")
    protected var evidence: List<Int>? = null

    /**
     * Gets the value of the key property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the key property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "key", required = true)
    var key: String = ""

    /**
     * Gets the value of the scope property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scope property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getScope().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [String]
     *
     *
     */
    fun getScopeList(): List<String>? {
        if (scope == null) {
            scope = ArrayList()
        }
        return scope
    }

    /**
     * Gets the value of the evidence property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evidence property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getEvidence().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [Integer]
     *
     *
     */
    fun getEvidenceList(): List<Int>? {
        if (evidence == null) {
            evidence = ArrayList()
        }
        return evidence
    }

}