//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 08:09:53 AM PDT 
//
package org.biographdb.alsdb.model.uniprot

import javax.xml.bind.annotation.*

/**
 *
 * Indicates whether the name of a plasmid is known or unknown.
 *
 *
 *
 * Java class for statusType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="statusType">
 * &lt;simpleContent>
 * &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 * &lt;attribute name="status" default="known">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="known"/>
 * &lt;enumeration value="unknown"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/attribute>
 * &lt;/extension>
 * &lt;/simpleContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "statusType", propOrder = ["value"])
class StatusType {
    /**
     * Gets the value of the value property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the value property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlValue
    var value: String? = null

    @XmlAttribute(name = "status")
    protected var status: String? = null

    /**
     * Gets the value of the status property.
     *
     * @return
     * possible object is
     * [String]
     */
//    fun getStatus(): String {
//        return if (status == null) {
//            "known"
//        } else {
//            status
//        }
//    }

    /**
     * Sets the value of the status property.
     *
     * @param value
     * allowed object is
     * [String]
     */
//    fun setStatus(value: String?) {
//        status = value
//    }
}