/*
 * Copyright (c) 2020. BioGraphDb
 * All rights reserved
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 08:09:53 AM PDT 
//
package org.biographdb.alsdb.model.uniprot

import java.util.*
import javax.xml.bind.annotation.*

/**
 *
 * Java class for anonymous complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element ref="{http://uniprot.org/uniprot}entry" maxOccurs="unbounded"/>
 * &lt;element ref="{http://uniprot.org/uniprot}copyright" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = ["entry", "copyright"])
@XmlRootElement(name = "uniprot")
class Uniprot {
    @XmlElement(required = true)
    protected var entry: List<Entry>? = null
    /**
     * Gets the value of the copyright property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the copyright property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    var copyright: String? = null

    /**
     * Gets the value of the entry property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entry property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getEntry().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [Entry]
     *
     *
     */
    fun resolveEntryList(): List<Entry> = entry.orEmpty()

    fun getEntryList(): List<Entry>? {
        if (entry == null) {
            entry = ArrayList()
        }
        return entry
    }

}